const data = {
    activities: [
      {
        name: 'Archery',
        type: 'solo',
        initialPlayers: 1,
        maxPlayers: 8,
        pointName: '',
        winner: 'high',
      },
      {
        name: 'Badminton',
        type: '1v1',
        initialPlayers: 2,
        maxPlayers: 2,
        pointName: '',
        winner: 'high',
      },
      {
        name: 'Baseball',
        type: '1v1',
        initialPlayers: 2,
        maxPlayers: 2,
        pointName: '',
        winner: 'high',
      },
      {
        name: 'Basketball',
        type: '1v1',
        initialPlayers: 2,
        maxPlayers: 2,
        pointName: '',
        winner: 'high',
      },
      {
        name: 'Boxing',
        type: '1v1',
        initialPlayers: 2,
        maxPlayers: 2,
        pointName: '',
        winner: 'high',
      },
      {
        name: 'Basketball',
        type: '1v1',
        initialPlayers: 2,
        maxPlayers: 2,
        pointName: '',
        winner: 'high',
      },
      {
        name: 'Cricket',
        type: '1v1',
        initialPlayers: 2,
        maxPlayers: 2,
        pointName: '',
        winner: 'high',
      },
      {
        name: 'Cycling',
        type: 'time/distance',
        initialPlayers: 1,
        maxPlayers: 4,
        pointName: 'km/m',
        winner: 'low',
      },
      {
        name: 'Fencing',
        type: '1v1',
        initialPlayers: 2,
        maxPlayers: 2,
        pointName: '',
        winner: 'high',
      },
      {
        name: 'Golf',
        type: 'solo',
        initialPlayers: 1,
        maxPlayers: 4,
        pointName: 'strokes',
        winner: 'low',
      },
      {
        name: 'Gymnastics',
        type: 'solo',
        initialPlayers: 1,
        maxPlayers: 4,
        pointName: '',
        winner: 'high',
      },
      {
        name: 'Hockey',
        type: '1v1',
        initialPlayers: 2,
        maxPlayers: 2,
        pointName: '',
        winner: 'high',
      },
      {
        name: 'Mixed Martial Arts',
        type: '1v1',
        initialPlayers: 2,
        maxPlayers: 2,
        pointName: '',
        winner: 'high',
      },
      {
        name: 'Rowing',
        type: 'time/distance',
        initialPlayers: 1,
        maxPlayers: 4,
        pointName: 'm/m',
        winner: 'low',
      },
      {
        name: 'Rugby',
        type: '1v1',
        initialPlayers: 2,
        maxPlayers: 2,
        pointName: '',
        winner: 'high',
      },
      {
        name: 'Running',
        type: 'time/distance',
        initialPlayers: 1,
        maxPlayers: 1,
        pointName: '',
        winner: 'low',
      },
      {
        name: 'Mixed Martial Arts',
        type: '1v1',
        initialPlayers: 2,
        maxPlayers: 2,
        pointName: '',
        winner: 'high',
      },
      {
        name: 'Skiing',
        type: 'time/distance',
        initialPlayers: 1,
        maxPlayers: 4,
        pointName: 'm/m',
        winner: 'low',
      },
      {
        name: 'Snowboarding',
        type: 'time/distance',
        initialPlayers: 1,
        maxPlayers: 4,
        pointName: 'm/m',
        winner: 'low',
      },
      {
        name: 'Swimming',
        type: 'time/distance',
        initialPlayers: 1,
        maxPlayers: 4,
        pointName: 'm/m',
        winner: 'low',
      },
      {
        name: 'Table Tennis',
        type: '1v1',
        initialPlayers: 2,
        maxPlayers: 2,
        pointName: '',
        winner: 'high',
      },
      {
        name: 'Tennis',
        type: '1v1',
        initialPlayers: 2,
        maxPlayers: 2,
        pointName: '',
        winner: 'high',
      },
      {
        name: 'Volleyball',
        type: '1v1',
        initialPlayers: 2,
        maxPlayers: 2,
        pointName: '',
        winner: 'high',
      },
      {
        name: 'Weight Lifting',
        type: 'weight',
        initialPlayers: 1,
        maxPlayers: 1,
        pointName: 'kg',
        winner: 'high',
      },
      {
        name: 'Weightlifting',
        type: 'weight',
        initialPlayers: 1,
        maxPlayers: 1,
        pointName: 'kg',
        winner: 'high',
      },
      {
        name: 'Wrestling',
        type: '1v1',
        initialPlayers: 2,
        maxPlayers: 2,
        pointName: '',
        winner: 'high',
      },
      {
        name: 'Weight Lifting',
        type: 'weight',
        initialPlayers: 1,
        maxPlayers: 1,
        pointName: 'kg',
        winner: 'high',
      },
    ]
}

export default data;
